version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./:/app

  # criar containeer mongo
  #   links:
  #     - db
  #   command: npm start
  # db:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   restart: always

