version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3333:3333"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev